# Generated by Django 3.0.6 on 2020-05-26 17:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('valorant', '0002_remove_agentpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpage',
            name='ability_a',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_a_desc',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_a_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_b',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_b_desc',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_b_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_sig',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_sig_desc',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_sig_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_ult',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_ult_desc',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_ult_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='origin',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='origin_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
    ]
