# Generated by Django 3.0.6 on 2020-05-26 17:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('valorant', '0003_auto_20200526_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpage',
            name='ability_a_cost',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_b_cost',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_sig_cost',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='ability_ult_cost',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='char_type',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='char_type_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='gun_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='gun_type',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentpage',
            name='gunbuddy_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
    ]
