# Generated by Django 3.0.6 on 2020-05-26 23:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('valorant', '0005_mappage_mapspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponsPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WeaponPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('weapon_type', wagtail.core.fields.RichTextField(blank=True)),
                ('cost', wagtail.core.fields.RichTextField(blank=True)),
                ('magazine', wagtail.core.fields.RichTextField(blank=True)),
                ('wall_pen', wagtail.core.fields.RichTextField(blank=True)),
                ('prim_fire_mode', wagtail.core.fields.RichTextField(blank=True)),
                ('prim_fire_rate', wagtail.core.fields.RichTextField(blank=True)),
                ('sec_fire_mode', wagtail.core.fields.RichTextField(blank=True)),
                ('sec_fire_rate', wagtail.core.fields.RichTextField(blank=True)),
                ('dam_short_body', wagtail.core.fields.RichTextField(blank=True)),
                ('dam_short_head', wagtail.core.fields.RichTextField(blank=True)),
                ('dam_short_leg', wagtail.core.fields.RichTextField(blank=True)),
                ('dam_long_body', wagtail.core.fields.RichTextField(blank=True)),
                ('dam_long_head', wagtail.core.fields.RichTextField(blank=True)),
                ('dam_long_leg', wagtail.core.fields.RichTextField(blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WeaponGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                            to='wagtailimages.Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE,
                                                         related_name='weapon_images', to='valorant.WeaponPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
