# Generated by Django 3.0.6 on 2020-05-28 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('valorant', '0006_weapongalleryimage_weaponpage_weaponspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpage',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
    ]
